//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> NetPrice { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsUrgent { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Operations Operations { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
