//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrders
    {
        public int Order_Id { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
